import type { ImageSourcePropType } from 'react-native';

export type IngredientImageEntry = {
  source: ImageSourcePropType;
  imageId: string;
};

/**
 * Ingredient image manifest mapping image IDs to their require() sources.
 *
 * Naming convention:
 * - Primary ingredient images (from herbs): use recipe ID as the image ID (e.g., "1", "2", ...)
 * - Secondary/placeholder images: use "placeholder" or specific IDs like "2", "2-2", etc.
 *
 * The manifest is keyed by imageId (string) for flexibility.
 * Images are stored in assets/ingredients/.
 *
 * NOTE: This manifest is auto-generated by scripts/update-ingredient-images.js
 */
export const ingredientImageManifest: Record<string, IngredientImageEntry> = {
  '1': { source: require('../../assets/ingredients/1.jpg'), imageId: '1' },
  '2': { source: require('../../assets/ingredients/2.jpg'), imageId: '2' },
  '3': { source: require('../../assets/ingredients/3.jpg'), imageId: '3' },
  '4': { source: require('../../assets/ingredients/4.jpg'), imageId: '4' },
  '5': { source: require('../../assets/ingredients/5.jpg'), imageId: '5' },
  '6': { source: require('../../assets/ingredients/6.jpg'), imageId: '6' },
  '7': { source: require('../../assets/ingredients/7.jpg'), imageId: '7' },
  '8': { source: require('../../assets/ingredients/8.jpg'), imageId: '8' },
  '9': { source: require('../../assets/ingredients/9.jpg'), imageId: '9' },
  '10': { source: require('../../assets/ingredients/10.jpg'), imageId: '10' },
  '11': { source: require('../../assets/ingredients/11.jpg'), imageId: '11' },
  '12': { source: require('../../assets/ingredients/12.jpg'), imageId: '12' },
  '13': { source: require('../../assets/ingredients/13.jpg'), imageId: '13' },
  '14': { source: require('../../assets/ingredients/14.jpg'), imageId: '14' },
  '15': { source: require('../../assets/ingredients/15.jpg'), imageId: '15' },
  '16': { source: require('../../assets/ingredients/16.jpg'), imageId: '16' },
  '17': { source: require('../../assets/ingredients/17.jpg'), imageId: '17' },
  '18': { source: require('../../assets/ingredients/18.jpg'), imageId: '18' },
  '19': { source: require('../../assets/ingredients/19.jpg'), imageId: '19' },
  '20': { source: require('../../assets/ingredients/20.jpg'), imageId: '20' },
  '21': { source: require('../../assets/ingredients/21.jpg'), imageId: '21' },
  '22': { source: require('../../assets/ingredients/22.jpg'), imageId: '22' },
  '23': { source: require('../../assets/ingredients/23.jpg'), imageId: '23' },
  '24': { source: require('../../assets/ingredients/24.jpg'), imageId: '24' },
  '25': { source: require('../../assets/ingredients/25.jpg'), imageId: '25' },
  '26': { source: require('../../assets/ingredients/26.jpg'), imageId: '26' },
  '27': { source: require('../../assets/ingredients/27.jpg'), imageId: '27' },
  '28': { source: require('../../assets/ingredients/28.jpg'), imageId: '28' },
  '29': { source: require('../../assets/ingredients/29.jpg'), imageId: '29' },
  '30': { source: require('../../assets/ingredients/30.jpg'), imageId: '30' },
  '31': { source: require('../../assets/ingredients/31.jpg'), imageId: '31' },
  '32': { source: require('../../assets/ingredients/32.jpg'), imageId: '32' },
  '33': { source: require('../../assets/ingredients/33.jpg'), imageId: '33' },
  '34': { source: require('../../assets/ingredients/34.jpg'), imageId: '34' },
  '35': { source: require('../../assets/ingredients/35.jpg'), imageId: '35' },
  '36': { source: require('../../assets/ingredients/36.jpg'), imageId: '36' },
  '37': { source: require('../../assets/ingredients/37.jpg'), imageId: '37' },
  '38': { source: require('../../assets/ingredients/38.jpg'), imageId: '38' },
  '39': { source: require('../../assets/ingredients/39.jpg'), imageId: '39' },
  '40': { source: require('../../assets/ingredients/40.jpg'), imageId: '40' },
  '41': { source: require('../../assets/ingredients/41.jpg'), imageId: '41' },
  '42': { source: require('../../assets/ingredients/42.jpg'), imageId: '42' },
  '43': { source: require('../../assets/ingredients/43.jpg'), imageId: '43' },
  '44': { source: require('../../assets/ingredients/44.jpg'), imageId: '44' },
  '45': { source: require('../../assets/ingredients/45.jpg'), imageId: '45' },
  '46': { source: require('../../assets/ingredients/46.jpg'), imageId: '46' },
  '47': { source: require('../../assets/ingredients/47.jpg'), imageId: '47' },
  '48': { source: require('../../assets/ingredients/48.jpg'), imageId: '48' },
  '49': { source: require('../../assets/ingredients/49.jpg'), imageId: '49' },
  '50': { source: require('../../assets/ingredients/50.jpg'), imageId: '50' },
  '51': { source: require('../../assets/ingredients/51.jpg'), imageId: '51' },
  '52': { source: require('../../assets/ingredients/52.jpg'), imageId: '52' },
  '53': { source: require('../../assets/ingredients/53.jpg'), imageId: '53' },
  '54': { source: require('../../assets/ingredients/54.jpg'), imageId: '54' },
  '55': { source: require('../../assets/ingredients/55.jpg'), imageId: '55' },
  '56': { source: require('../../assets/ingredients/56.jpg'), imageId: '56' },
  '57': { source: require('../../assets/ingredients/57.jpg'), imageId: '57' },
  '58': { source: require('../../assets/ingredients/58.jpg'), imageId: '58' },
  '59': { source: require('../../assets/ingredients/59.jpg'), imageId: '59' },
  '60': { source: require('../../assets/ingredients/60.jpg'), imageId: '60' },
  '61': { source: require('../../assets/ingredients/61.jpg'), imageId: '61' },
  '62': { source: require('../../assets/ingredients/62.jpg'), imageId: '62' },
  '63': { source: require('../../assets/ingredients/63.jpg'), imageId: '63' },
  '64': { source: require('../../assets/ingredients/64.jpg'), imageId: '64' },
  '65': { source: require('../../assets/ingredients/65.jpg'), imageId: '65' },
  '66': { source: require('../../assets/ingredients/66.jpg'), imageId: '66' },
  '67': { source: require('../../assets/ingredients/67.jpg'), imageId: '67' },
  '68': { source: require('../../assets/ingredients/68.jpg'), imageId: '68' },
  '69': { source: require('../../assets/ingredients/69.jpg'), imageId: '69' },
  '70': { source: require('../../assets/ingredients/70.jpg'), imageId: '70' },
  '71': { source: require('../../assets/ingredients/71.jpg'), imageId: '71' },
  '72': { source: require('../../assets/ingredients/72.jpg'), imageId: '72' },
  '73': { source: require('../../assets/ingredients/73.jpg'), imageId: '73' },
  '74': { source: require('../../assets/ingredients/74.jpg'), imageId: '74' },
  '75': { source: require('../../assets/ingredients/75.jpg'), imageId: '75' },
  '76': { source: require('../../assets/ingredients/76.jpg'), imageId: '76' },
  '77': { source: require('../../assets/ingredients/77.jpg'), imageId: '77' },
  '78': { source: require('../../assets/ingredients/78.jpg'), imageId: '78' },
  '79': { source: require('../../assets/ingredients/79.jpg'), imageId: '79' },
  '80': { source: require('../../assets/ingredients/80.jpg'), imageId: '80' },
  '81': { source: require('../../assets/ingredients/81.jpg'), imageId: '81' },
  '82': { source: require('../../assets/ingredients/82.jpg'), imageId: '82' },
  '83': { source: require('../../assets/ingredients/83.jpg'), imageId: '83' },
  '84': { source: require('../../assets/ingredients/84.jpg'), imageId: '84' },
  '85': { source: require('../../assets/ingredients/85.jpg'), imageId: '85' },
  '86': { source: require('../../assets/ingredients/86.jpg'), imageId: '86' },
  '87': { source: require('../../assets/ingredients/87.jpg'), imageId: '87' },
  '88': { source: require('../../assets/ingredients/88.jpg'), imageId: '88' },
  '89': { source: require('../../assets/ingredients/89.jpg'), imageId: '89' },
  '90': { source: require('../../assets/ingredients/90.jpg'), imageId: '90' },
  '91': { source: require('../../assets/ingredients/91.jpg'), imageId: '91' },
  '92': { source: require('../../assets/ingredients/92.jpg'), imageId: '92' },
  '93': { source: require('../../assets/ingredients/93.jpg'), imageId: '93' },
  '94': { source: require('../../assets/ingredients/94.jpg'), imageId: '94' },
  '95': { source: require('../../assets/ingredients/95.jpg'), imageId: '95' },
  '96': { source: require('../../assets/ingredients/96.jpg'), imageId: '96' },
  '97': { source: require('../../assets/ingredients/97.jpg'), imageId: '97' },
  '98': { source: require('../../assets/ingredients/98.jpg'), imageId: '98' },
  '99': { source: require('../../assets/ingredients/99.jpg'), imageId: '99' },
  '100': { source: require('../../assets/ingredients/100.jpg'), imageId: '100' },
};

/**
 * Fallback placeholder source when no image is available.
 * Returns null to indicate no image should be displayed.
 */
export const INGREDIENT_IMAGE_PLACEHOLDER: ImageSourcePropType | null = null;
